namespace DreamSoft.Domain.Common;

/// <summary>
/// Base entity with only identity (ID)
/// All entities in the system inherit from this
/// </summary>
public abstract class BaseEntity
{
    /// <summary>
    /// Unique identifier - Auto-generated by database
    /// </summary>
    public int Id { get; protected init; }
}